name: check_template

on:
  workflow_call:
    inputs:
      integration_name:
        required: true
        type: string
      deprecated:
        required: true
        type: boolean
      extra_cmds:
        required: false
        type: string
      python_matrix:
        required: false
        type: string
        default: "['3.8', '3.9', '3.10', '3.11']"
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Check Integration Name
        run: |
          echo "Input is ${{ inputs.integration_name }}"
      - name: Install Common Dependencies
        run: |
          python -m pip install -U pip
          pip install --progress-bar off -U .[checking]
          pip install --progress-bar off -U .[test]

      - name: Install Integration Dependencies
        if: ${{ !inputs.deprecated }}
        run: |
          pip install --progress-bar off .[${{ inputs.integration_name }}]

      - name: Black
        run: |
          if [ -e optuna_sklearn_integration/${{ inputs.integration_name }} ]; then
            black optuna_sklearn_integration/${{ inputs.integration_name }} --check --diff
          fi
          if [ -e tests/${{ inputs.integration_name }} ]; then
            black tests/${{ inputs.integration_name }} --check --diff
          fi

      - name: Import Sorting
        run: |
          if [ -e optuna_sklearn_integration/${{ inputs.integration_name }} ]; then
            isort optuna_sklearn_integration/${{ inputs.integration_name }} --check --diff
          fi
          if [ -e tests/${{ inputs.integration_name }} ]; then
            isort tests/${{ inputs.integration_name }} --check --diff
          fi

      - name: MyPy
        run: |
          if [ -e optuna_sklearn_integration/${{ inputs.integration_name }} ]; then
            mypy optuna_sklearn_integration/${{ inputs.integration_name }}
          fi
          if [ -e tests/${{ inputs.integration_name }} ]; then
            mypy tests/${{ inputs.integration_name }}
          fi

      - name: BlackDoc
        run: |
          if [ -e optuna_sklearn_integration/${{ inputs.integration_name }} ]; then
            blackdoc optuna_sklearn_integration/${{ inputs.integration_name }} --check --diff
          fi
          if [ -e tests/${{ inputs.integration_name }} ]; then
            blackdoc tests/${{ inputs.integration_name }} --check --diff
          fi

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python_matrix) }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Common Dependencies
      run: |
        python -m pip install --upgrade pip

        # Install optuna from optuna master
        pip install git+https://github.com/optuna/optuna@master
        pip install --progress-bar off .[test]

    - name: Install Integration Dependencies
      if: ${{ !inputs.deprecated }}
      run: |
        pip install --progress-bar off .[${{ inputs.integration_name }}]

    - name: Extra Commands
      run: |
        ${{ inputs.extra_cmds }}

    - name: Tests
      run: |
        if [ -e tests/${{ inputs.integration_name }} ]; then
          pytest tests/${{ inputs.integration_name }}
        fi
