name: Checks and Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Common Dependencies
        run: |
          python -m pip install -U pip
          pip install --progress-bar off -U .[checking]
          pip install --progress-bar off -U .[test]

      - name: Install Integration Dependencies
        if: ${{ !inputs.deprecated }}
        run: |
          pip install --progress-bar off .

      - name: Black
        run: |
          if [ -e optuna_sklearn_integration/ ]; then
            black optuna_sklearn_integration/ --check --diff
          fi
          if [ -e tests/ ]; then
            black tests/ --check --diff
          fi

      - name: Import Sorting
        run: |
          if [ -e optuna_sklearn_integration/ ]; then
            isort optuna_sklearn_integration/ --check --diff
          fi
          if [ -e tests/ ]; then
            isort tests/ --check --diff
          fi

      - name: MyPy
        run: |
          if [ -e optuna_sklearn_integration/ ]; then
            mypy optuna_sklearn_integration/
          fi
          if [ -e tests/ ]; then
            mypy tests/
          fi

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python_matrix) }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Common Dependencies
      run: |
        python -m pip install --upgrade pip

        # Install optuna from optuna master
        pip install git+https://github.com/optuna/optuna@master
        pip install --progress-bar off .[test]

    - name: Install Integration Dependencies
      if: ${{ !inputs.deprecated }}
      run: |
        pip install --progress-bar off .

    - name: Extra Commands
      run: |
        ${{ inputs.extra_cmds }}

    - name: Tests
      run: |
        if [ -e tests/ ]; then
          pytest tests/
        fi
